---
title: "Exploratory Data Analysis: Country"
output: word_document
date: "2023-09-11"
---


```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  fig.width = 6,
  fig.asp = 0.618,
  out.width = "99%",
  fig.align = "center",
  dpi = 300
)
options(scipen = 999, digits = 4)
knitr::knit_hooks$set(
  inline = function(x) {
    if (is.numeric(x)) {
      return(prettyNum(x, big.mark = ","))
    } else{
      return(x)
    }
  }
)
```

```{r dependencies}
library(tidyverse, warn.conflicts = FALSE)
library(cowplot)
```

```{r data_prep}
library(hoaddata)

# ta_oa_inst <- readr::read_csv("https://storage.googleapis.com/hoaddata/ta_oa_inst.csv.gz")
ta_oa_inst <- readr::read_csv(here::here("data/ta_oa_inst.csv.gz"))
# add country codes
ror_country_codes <- readr::read_csv(here::here("data/ror_country_codes.csv"))
# Join
my_df <- inner_join(ta_oa_inst, ror_country_codes, by = "ror_main")

## Articles under TA
ta_df <- my_df |>
  group_by(cr_year, issn_l, country_code, cc) |>
  summarise(ta_inst_articles = n_distinct(doi),
            ta_active_articles = length(unique(doi[ta_active == TRUE])))

## Join with hoaddata affiliation data
aff_ta <- left_join(hoaddata::jn_aff, ta_df, by = c("issn_l", "cr_year", "country_code", "cc")) |>
  # Just TA 
  filter(issn_l %in% hoaddata::jct_hybrid_jns$issn_l, issn_l != "0027-8424")
```

- Proportion of inst per countries with at least one ta 

```{r}
aff_country_all <- aff_ta |>
  distinct(issn_l, cr_year, country_code, articles_total) |>
  group_by(cr_year, country_code) |>
  summarise(articles = sum(articles_total, na.rm = TRUE))
aff_ta_all <- aff_ta |>
  group_by(cr_year, country_code) |>
  summarise(ta_inst_articles = sum(ta_inst_articles, na.rm = TRUE))
aff_oa_ta <- aff_ta |> 
  filter(!is.na(cc)) |>
  group_by(cr_year, country_code) |>
  summarise(cc_articles = sum(articles_under_cc_variant, na.rm = TRUE),
            ta_active_oa_articles = sum(ta_active_articles, na.rm = TRUE))
tmp <- aff_country_all |>
  left_join(aff_ta_all) |>
  left_join(aff_oa_ta) |>
  mutate(no_ta_articles = articles - ta_inst_articles, 
         no_ta_oa = cc_articles - ta_active_oa_articles)
```

### plot test

```{r}
library(ggrepel)
p <- tmp |>
  filter(cr_year == 2022, !is.na(country_code), articles > 1000) |>
  ggplot(aes(articles, cc_articles )) +
  geom_point(aes(fill = ta_active_oa_articles / cc_articles), color = "grey50", shape = 21, alpha = 0.8, size = 5) +
 scale_fill_distiller("TA OA", palette = "RdYlBu", direction = 1) +
    geom_smooth(data = filter(tmp, !country_code %in% c("CH", "US")), aes(articles, cc_articles ), method=lm) +
  ggrepel::geom_text_repel(
    data = filter(tmp, cr_year == 2022, articles > 12000),
    aes(x = articles, y = cc_articles, label = country_code),
    force = 50,
    box.padding = 0.5,
    point.padding = 0.8,
    size = 5,
    max.iter = 1000000,
    max.overlaps = Inf,
    min.segment.length = 0,
    arrow = arrow(length = unit(0.010, "npc"))) +
#    scale_y_continuous(labels =  scales::number_format(big.mark = " ")) +
    scale_x_continuous(labels =  scales::number_format(big.mark = " ")) +
  theme_minimal() +
  theme(legend.position="top", legend.justification = "center") 


 qq <- tmp |>
  filter(cr_year == 2022, !is.na(country_code), articles > 1000) |>
  ggplot(aes(ta_active_oa_articles, cc_articles)) +
  geom_point(aes(fill = ta_active_oa_articles / cc_articles), color = "grey50", shape = 21, alpha = 0.8, size = 5) +
 scale_fill_distiller("TA OA", palette = "RdYlBu", direction = 1) +
 #   geom_smooth(method=lm) +
  ggrepel::geom_text_repel(
    data = filter(tmp, cr_year == 2022, articles > 12000),
    aes(x = ta_active_oa_articles, y =  cc_articles, label = country_code),
    force = 50,
    box.padding = 0.5,
    point.padding = 0.8,
    size = 5,
    max.iter = 1000000,
    max.overlaps = Inf,
    min.segment.length = 0,
    arrow = arrow(length = unit(0.010, "npc"))) +
#    scale_y_continuous(labels =  scales::number_format(big.mark = " ")) +
    scale_x_continuous(labels =  scales::number_format(big.mark = " ")) +
 #  scale_x_log10() +
  theme_minimal() +
  theme(legend.position="top", legend.justification = "center") 
```

with pie charts

```{r}
# library(ggrepel)
# library(scatterpie)
# df_22 <- tmp |>
#   filter(cr_year == 2022, !is.na(country_code), !is.na(ta_active_oa_articles)) |>
#   mutate(ta_active_oa_articles_ = ta_active_oa_articles,
#          log_articles = log(articles))
# p <- df_22 |>
#   ggplot() +
#   geom_scatterpie(data = df_22, aes(articles, cc_articles, group = country_code), cols=c("ta_active_oa_articles_", "no_ta_oa")) +
#   geom_smooth(aes(articles, cc_articles), method=lm) +
#   #coord_fixed() +
#    ggrepel::geom_text_repel(
#     data = filter(df_22, cc_articles > 2000),
#     aes(x = articles, y = cc_articles, label = country_code),
#     force = 50,
#     box.padding = 1,
#     size = 4,
#     max.iter = 1000,
#     max.overlaps = Inf,
#     min.segment.length = 0,
#     arrow = arrow(length = unit(0.010, "npc"))) 
```

